apiVersion: v1
kind: Service
metadata: # kpt-merge: /nrf-nnrf
  name: nrf-nnrf
  labels:
    app.kubernetes.io/version: "v3.1.1"
    project: free5gc
    nf: nrf
  annotations:
    internal.kpt.dev/upstream-identifier: '|Service|default|nrf-nnrf'
  namespace: free5gc-cp
spec:
  type: ClusterIP
  ports:
  - port: 8000
    targetPort: 8000
    protocol: TCP
    name: http
  selector:
    project: free5gc
    nf: nrf
