apiVersion: v1
kind: Service
metadata:
  name: oairfsimgnb
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - name: n3
      port: 2152
      targetPort: 2152
      protocol: UDP
    - name: n2
      port: 36412
      targetPort: 36412
      protocol: SCTP
  selector:
    app.kubernetes.io/name: oairfsimgnb
    app.kubernetes.io/instance: oairfsimgnb