apiVersion: config.porch.kpt.dev/v1alpha1
kind: PackageVariant
metadata: # kpt-merge: /example-cluster
  name: regional-cluster
  annotations:
    internal.kpt.dev/upstream-identifier: 'config.porch.kpt.dev|PackageVariant|default|example-cluster'
spec:
  annotations:
    approval.nephio.org/policy: initial
  upstream:
    package: cluster-capi-kind
    repo: catalog-infra-capi
    revision: v2.0.0
  downstream:
    package: regional-cluster
    repo: mgmt
  injectors:
  - kind: WorkloadCluster
    name: regional
  pipeline:
    mutators:
    - image: gcr.io/kpt-fn/set-annotations:v0.1.4
      configMap:
        nephio.org/cluster-name: regional
