apiVersion: config.porch.kpt.dev/v1alpha1
kind: PackageVariant
metadata: # kpt-merge: /example-kindnet
  name: regional-kindnet
  annotations:
    internal.kpt.dev/upstream-identifier: 'config.porch.kpt.dev|PackageVariant|default|example-kindnet'
spec:
  annotations:
    approval.nephio.org/policy: initial
  upstream:
    package: kindnet
    repo: catalog-infra-capi
    revision: v2.0.0
  downstream:
    package: regional-kindnet
    repo: mgmt-staging
  pipeline:
    mutators:
    - image: gcr.io/kpt-fn/set-annotations:v0.1.4
      configMap:
        nephio.org/cluster-name: regional
