apiVersion: config.porch.kpt.dev/v1alpha1
kind: PackageVariant
metadata: # kpt-merge: /example-vlanindex
  name: regional-vlanindex
  annotations:
    internal.kpt.dev/upstream-identifier: 'config.porch.kpt.dev|PackageVariant|default|example-vlanindex'
  labels:
    nephio.org/region: it
    nephio.org/site-type: regional
spec:
  annotations:
    approval.nephio.org/policy: initial
  upstream:
    package: vlanindex
    repo: catalog-infra-capi
    revision: v2.0.0
  downstream:
    package: regional-vlanindex
    repo: mgmt
  injectors:
  - kind: WorkloadCluster
    name: regional
  pipeline:
    mutators:
    - image: gcr.io/kpt-fn/set-annotations:v0.1.4
      configMap:
        nephio.org/cluster-name: regional
