apiVersion: config.porch.kpt.dev/v1alpha1
kind: Repository
metadata: # kpt-merge: default/oai-packages
  name: oai-packages
  namespace: default
  labels:
    kpt.dev/repository-access: read-only
    kpt.dev/repository-content: external-blueprints
  annotations:
    internal.kpt.dev/upstream-identifier: 'config.porch.kpt.dev|Repository|default|oai-packages'
spec:
  content: Package
  deployment: false
  git:
    branch: v2.0.0
    directory: /
    repo: https://github.com/OPENAIRINTERFACE/oai-packages
  type: git
