apiVersion: v1
kind: Service
metadata: # kpt-merge: /udm-nudm
  name: udm-nudm
  labels:
    app.kubernetes.io/version: "v3.1.1"
    project: free5gc
    nf: udm
  annotations:
    internal.kpt.dev/upstream-identifier: '|Service|default|udm-nudm'
  namespace: free5gc-cp
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
  selector:
    project: free5gc
    nf: udm
