apiVersion: v1
kind: ConfigMap
metadata: # kpt-merge: /udm-configmap
  name: udm-configmap
  labels:
    app.kubernetes.io/version: "v3.1.1"
    app: free5gc
  annotations:
    internal.kpt.dev/upstream-identifier: '|ConfigMap|default|udm-configmap'
  namespace: free5gc-cp
data:
  udmcfg.yaml: "info:\n  version: 1.0.2\n  description: UDM initial local configuration\n\nconfiguration:\n  serviceNameList:\n    - nudm-sdm\n    - nudm-uecm\n    - nudm-ueau\n    - nudm-ee\n    - nudm-pp\n  \n  sbi:\n    scheme: http\n    registerIPv4: udm-nudm # IP used to register to NRF\n    bindingIPv4: 0.0.0.0  # IP used to bind the service\n    port: 80\n    tls:\n      key: config/TLS/udm.key\n      pem: config/TLS/udm.pem\n  \n  nrfUri: http://nrf-nnrf:8000\n  # test data set from TS33501-f60 Annex C.4\n  SuciProfile:\n    - ProtectionScheme: 1 # Protect Scheme: Profile A\n      PrivateKey: c53c22208b61860b06c62e5406a7b330c2b577aa5558981510d128247d38bd1d\n      PublicKey: 5a8d38864820197c3394b92613b20b91633cbd897119273bf8e4a6f4eec0a650\n    - ProtectionScheme: 2 # Protect Scheme: Profile B\n      PrivateKey: F1AB1074477EBCC7F554EA1C5FC368B1616730155E0041AC447D6301975FECDA\n      PublicKey: 0472DA71976234CE833A6907425867B82E074D44EF907DFB4B3E21C1C2256EBCD15A7DED52FCBB097A4ED250E036C7B9C8C7004C4EEDC4F068CD7BF8D3F900E3B4\n\nlogger:\n  UDM:\n    ReportCaller: false\n    debugLevel: info\n"
