apiVersion: v1
kind: Service
metadata: # kpt-merge: /ausf-nausf
  name: ausf-nausf
  labels:
    app.kubernetes.io/version: "v3.1.1"
    project: free5gc
    nf: ausf
  annotations:
    internal.kpt.dev/upstream-identifier: '|Service|default|ausf-nausf'
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
  selector:
    project: free5gc
    nf: ausf
