apiVersion: v1
kind: ConfigMap
metadata: # kpt-merge: /pcf-configmap
  name: pcf-configmap
  labels:
    app.kubernetes.io/version: "v3.1.1"
    app: free5gc
  annotations:
    internal.kpt.dev/upstream-identifier: '|ConfigMap|default|pcf-configmap'
  namespace: free5gc-cp
data:
  pcfcfg.yaml: "info:\n  version: 1.0.1\n  description: PCF initial local configuration\n\nconfiguration:\n  serviceList:\n    - serviceName: npcf-am-policy-control\n    - serviceName: npcf-smpolicycontrol\n      suppFeat: 3fff\n    - serviceName: npcf-bdtpolicycontrol\n    - serviceName: npcf-policyauthorization\n      suppFeat: 3\n    - serviceName: npcf-eventexposure\n    - serviceName: npcf-ue-policy-control\n\n  sbi:\n    scheme: http\n    registerIPv4: pcf-npcf  # IP used to register to NRF\n    bindingIPv4: 0.0.0.0    # IP used to bind the service\n    port: 80\n    tls:\n      key: config/TLS/pcf.key\n      pem: config/TLS/pcf.pem\n  \n  mongodb:       # the mongodb connected by this PCF\n    name: free5gc                  # name of the mongodb\n    url: mongodb://mongodb:27017 # a valid URL of the mongodb\n  \n  nrfUri: http://nrf-nnrf:8000\n  pcfName: PCF\n  timeFormat: 2019-01-02 15:04:05\n  defaultBdtRefId: BdtPolicyId-\n  locality: area1\n\nlogger:\n  PCF:\n    ReportCaller: false\n    debugLevel: info\n"
