apiVersion: v1
kind: Service
metadata: # kpt-merge: /udr-nudr
  name: udr-nudr
  labels:
    app.kubernetes.io/version: "v3.1.1"
    project: free5gc
    nf: udr
  annotations:
    internal.kpt.dev/upstream-identifier: '|Service|default|udr-nudr'
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
  selector:
    project: free5gc
    nf: udr
