apiVersion: v1
kind: ConfigMap
metadata: # kpt-merge: /webui-configmap
  name: webui-configmap
  labels:
    app.kubernetes.io/version: "v3.1.1"
    app: free5gc
  annotations:
    internal.kpt.dev/upstream-identifier: '|ConfigMap|default|webui-configmap'
  namespace: free5gc-cp
data:
  webuicfg.yaml: "info:\n  version: 1.0.0\n  description: WEBUI initial local configuration\n\nconfiguration:\n  mongodb:\n    name: free5gc\n    url: mongodb://mongodb:27017\n    \nlogger:\n  WEBUI:\n    ReportCaller: false\n    debugLevel: info\n"
