apiVersion: workload.nephio.org/v1alpha1
kind: NFDeployment
metadata:
  name: amf-example
  namespace: amf-example
spec:
  provider: amf.openairinterface.org
  parametersRefs:
  - name: oai-amf-config
    apiVersion: workload.nephio.org/v1alpha1
    kind: NFConfig
    
